var el;

el = document.querySelector(".div1-1");
el2 = document.querySelector(".div1-2");
el3 = document.querySelector(".div1-3");
el4 = document.querySelector(".div1-4");
el5 = document.querySelector(".div1-5");
el6 = document.querySelector(".div1-6");
el6blue = document.querySelector(".div1-6blue");
el7 = document.querySelector(".div1-7");
el8 = document.querySelector(".div1-8");
setTimeout(() => (el.style.animation = "fadeOut ease 3s"), 300);
setTimeout(() => (el.style.visibility = "hidden"), 2300);
setTimeout(() => (el2.style.animation = "fadeOut ease 3s"), 2600);
setTimeout(() => (el2.style.visibility = "hidden"), 4490);
setTimeout(() => (el3.style.animation = "fadeOut ease 4s"), 4500);
setTimeout(() => (el3.style.visibility = "hidden"), 7500);
setTimeout(() => (el4.style.animation = "fadeOut ease 3s"), 7700);
setTimeout(() => (el4.style.visibility = "hidden"), 10000);
setTimeout(() => (el5.style.animation = "fadeOut ease 4s"), 10700);
setTimeout(() => (el5.style.visibility = "hidden"), 13700);
setTimeout(() => (el6.style.animation = "fadeOut ease 5s"), 14300);
setTimeout(() => (el6blue.style.color = "blue"), 16800);
setTimeout(() => (el6.style.visibility = "hidden"), 18300);
setTimeout(() => (el7.style.animation = "fadeOut ease 4s"), 18700);
setTimeout(() => (el7.style.visibility = "hidden"), 21700);
setTimeout(() => (el8.style.animation = "fadeOut ease 2s"), 22100);
setTimeout(() => (el8.style.color = "red"), 23200);
setTimeout(() => (el8.style.visibility = "hidden"), 23500);
